spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          contentType: application/*+avro
          destination: spring_cloud_config_channel
      schema-registry-client:
        endpoint: http://localhost:8080
      schema:
        avro:
          schema-locations: classpath:avro/cloudevent.avsc
server.port: 9010